// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.koderme.grpc.proto.greeting;

public interface GreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greeting.GreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
