// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.koderme.grpc.proto.greeting;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greeting.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();
}
